### PR TITLE
Add support for typed __version__ substitution.

### PR DESCRIPTION
**Pull request by da2ce7**
* Includes basic reformatting of the `substitution` section in the readme.

### CODE REVIEW

**Comment by mtkennerly** [comment]
Hi! Thank you for the PR, and I apologize for the late reply. However, there are a couple of issues here:

* `str` is correct, but I don't think it's necessary to be so explicitly restrictive. I'd rather just use something like `.*?`. Someone could use some slightly different formatting or a type alias, and although it would be unusual, I don't think there's any particular reason to exclude it in the regex.
* I prefer the original formatting for the README. I think it's more consistent with the rest of the document.

**Comment by da2ce7** [comment]
Hello @mtkennerly,

You have closed this pull request, would you like me to try and address your comments. Or are you planning to include support for the typed __version__ substitution on your own?

**Comment by mtkennerly** [comment]
I'd be happy to accept the PR if you'd still like to address the comments \:) I just wasn't sure how soon you'd see this since I replied late.

**Comment by mtkennerly** [comment]
Closing in favor of b40453b66bcf025aa2f4f5897795d2a9e548745d.

**Comment by da2ce7** [comment]
@mtkennerly thank you, just now I was meaning to get around to addressing the comments and now see you have fixed it already 👍.

**Pull request closed without merging**
